name: MacOS-ustk

# https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * SUN'

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre#comment133398800_72408109
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print system information
      run: |
        sysctl -a | grep machdep.cpu
        sysctl -a | grep logical

    - name: Print OS information
      run: system_profiler SPSoftwareDataType

    - name: Install dependencies
      run: brew install libpng libjpeg-turbo opencv vtk fftw armadillo

    - name: Clone visp-images
      run: |
        git clone --depth 1 https://github.com/lagadic/visp-images ${HOME}/visp-images
        echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Clone ustk-dataset
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk-dataset ${HOME}/ustk-dataset
        echo "USTK_DATASET_PATH=$HOME/ustk-dataset" >> $GITHUB_ENV
        echo ${USTK_DATASET_PATH}

    - name: Clone visp
      run: |
        git clone --depth 1 https://github.com/lagadic/visp ${HOME}/visp

    - name: Clone ustk-sample
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk-sample ${HOME}/ustk-sample

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ${HOME}/visp -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/usr/local -DVISP_CONTRIB_MODULES_PATH=${GITHUB_WORKSPACE}/modules
        cat ViSP-third-party.txt

    - name: Compile
      working-directory: build
      run: make -j$(sysctl -n hw.logicalcpu) install

    - name: Run unit tests
      working-directory: build
      run: ctest -j$(sysctl -n hw.logicalcpu) --output-on-failure

    - name: ViSP + UsTK as 3rdparty with cmake
      run: |
        cd ${HOME}/ustk-sample
        mkdir ustk-sample-build
        cd ustk-sample-build
        cmake .. -DVISP_DIR=/tmp/usr/local/lib/cmake/visp
        make -j$(sysctl -n hw.logicalcpu)
