name: Windows - Visual 2019
on:
  pull_request:
    types: [opened, reopened, synchronize]

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre#comment133398800_72408109
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest]

        include:
          - name: windows-latest
            os: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Display the workspace path
      working-directory: ${{ github.workspace }}
      run: pwd

    - name: Clone visp
      shell: bash
      run: |
        git clone --depth 1 https://github.com/lagadic/visp ${HOME}/visp

    - name: Clone visp-images
      shell: bash
      run: |
        git clone --depth 1 https://github.com/lagadic/visp-images ${HOME}/visp-images
        echo "VISP_INPUT_IMAGE_PATH=$HOME/visp-images" >> $GITHUB_ENV

    - name: Clone ustk-dataset
      shell: bash
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk-dataset ${HOME}/ustk-dataset
        echo "USTK_DATASET_PATH=$HOME/ustk-dataset" >> $GITHUB_ENV
        echo ${USTK_DATASET_PATH}

    - name: Configure ViSP
      working-directory: ${{ github.workspace }}
      run: |
        set VISP_INPUT_IMAGE_PATH=${{ env.VISP_INPUT_IMAGE_PATH }}
        set USTK_DATASET_PATH=${{ env.USTK_DATASET_PATH }}
        echo "VISP_INPUT_IMAGE_PATH: "
        echo %VISP_INPUT_IMAGE_PATH%
        echo "USTK_DATASET_PATH: "
        echo %USTK_DATASET_PATH%
        mkdir build
        cd build
        cmake ${HOME}/visp -G "Visual Studio 17 2022" -A "x64" -DVISP_CONTRIB_MODULES_PATH=.. -DBUILD_MODULE_visp_ar=OFF -DBUILD_MODULE_visp_blob=OFF -DBUILD_MODULE_visp_detection=OFF -DBUILD_MODULE_visp_klt=OFF -DBUILD_MODULE_visp_mbt=OFF -DBUILD_MODULE_visp_me=OFF -DBUILD_MODULE_visp_tt=OFF -DBUILD_MODULE_visp_tt_mi=OFF -DBUILD_MODULE_visp_vision=OFF -DBUILD_MODULE_visp_visual_features=OFF -DBUILD_MODULE_visp_vs=OFF
        type ViSP-third-party.txt

    - name: Build UsTK
      working-directory: ${{ github.workspace }}\build
      run: |
        cmake --build . --config Release

    - name: Install UsTK
      working-directory: ${{ github.workspace }}\build
      run: |
        cmake --build . --config Release --target install

    - name: Check installation folder
      working-directory: ${{ github.workspace }}\build
      run: |
        dir ${{ github.workspace }}\build\install\x64\vc17\bin

    - name: Test ViSP
      working-directory: ${{ github.workspace }}\build
      run: |
        set VISP_INPUT_IMAGE_PATH=${{ env.VISP_INPUT_IMAGE_PATH }}
        echo "VISP_INPUT_IMAGE_PATH: "
        echo %VISP_INPUT_IMAGE_PATH%
        set PATH=%PATH%;${{ github.workspace }}\build\install\x64\vc17\bin
        echo "PATH: "
        echo %PATH%
        ctest --output-on-failure -C Release -V
